# Using PangaeaDataset in PyeloTUPS

This tutorial demonstrates how to use `PangaeaDataset` to discover, explore,
and retrieve paleoceanographic datasets from PANGAEA.

Unlike `NOAADataset`, which interacts with the NOAA NCEI Paleo API,
`PangaeaDataset` communicates with the PANGAEA backend via `pangaeapy`,
while exposing a similar researcher-facing API.

### Requirements

Installation of ```pyleotups [version > {0.0.1}]``` automatically handles the installation of external services required for accessing the Pangaea Datasets.

In this tutorial, we will cover:

0. **Credentials setup** [Optional] Setting up credentials to access private datasets
1.  **Searching** for studies using the Pangaea.
2.  **Browsing** search results (Publications, Geography, Funding).
3.  **Extracting** data into pandas DataFrames.

### 0. Credential Setup

Few datasets over Panagaea are protected and reuqires the user to have an ACCESS KEY. 

Follow the instructions to access and set the key through pyleotups utilities. You can also do the steps manually.

<details>
<summary><strong>1. Obtaining Your PANGAEA API Token</summary></strong>

1. Create an account or log in at:  
   https://www.pangaea.de/user/login.php  

2. After logging in, navigate to your PANGAEA profile.

3. Locate your **API login token key**.

4. Copy this token — it is unique to your account.

> Keep this key private. It grants access to datasets associated with your account and other personal information.

<details>
<summary><strong>2. Securely Storing Your Token</summary></strong>

To prevent accidental exposure of your API key in notebooks or version control, we recommend storing it in a local `.env` file.

PyeloTUPS provides a helper utility to securely manage this for you.



#### Step 1 — Save Your Credentials (One-Time Setup)

```python
from pyleotups import save_pangaea_credentials

save_pangaea_credentials("your_token_here")
```

#### Step 2 — Load Credentials in Your Notebook

```python
from pyleotups import load_pangaea_credentials

pan_api = load_pangaea_credentials()
```
The variable pan_api now securely contains your login token.
</details>

<details>
<summary><strong>3. Managing pangaea credentials manually</strong></summary>

<br>
Installation of `pyleotups` (version > 0.0.1) automatically installs the external dependencies required to access PANGAEA datasets.

However, some datasets on PANGAEA are **protected** and require an **ACCESS KEY** (login token) for authentication.



#### Obtaining Your PANGAEA Access Key

1. Create an account or log in (for existing users) at:
   [https://www.pangaea.de/user/login.php](https://www.pangaea.de/user/login.php)

2. After logging in, navigate to your **PANGAEA profile**.

3. Locate your **login token key** in your profile settings.

> This token is unique to each user and should be kept private. 


### Securely Storing Your Token Using `dotenv`

To protect your personal credentials and prevent accidental exposure (e.g., when sharing notebooks), we strongly recommend using a `.env` file.

#### Step 1: Create a .env File

* In your project’s root directory, create a file named exactly:

```
.env
```

#### Step 2: Add Your API Token

Inside the .env file, add the following line:

```
PANGAEA_API="{your pangaea login token key}"
```

> If you use source control, we strongly recommend adding .env to your .gitignore files to exclude the .env file from being commited.
 
**Important:**

* The key must be enclosed in **double quotes**.
* Do **not** share this `.env` file when distributing notebooks or code.

---

### Accessing the Token in Your Notebook

In your Python notebook or script, load the token as follows:

```python
from dotenv import load_dotenv
import os
load_dotenv()
pan_api = os.getenv("PANGAEA_API")
```

The variable `pan_api` now securely contains your PANGAEA login token and can be used for accessing protected datasets.
</details>

In [ ]:
from pyleotups import save_pangaea_credentials, load_pangaea_credentials

### save_pangaea_credentials("your_api_key_here")
### remove the above line after saving your credentials, and then you can load them using the line below

pan_api = load_pangaea_credentials()

### 1. Searching for Studies

In [ ]:
import pyleotups as pt

# Initialize a Pangaea Dataset manager
# This object will act as your session, storing search results and processing data.
dataset = pt.PangaeaDataset(auth_token=pan_api)


The `search_studies()` method queries the PANGAEA backend
and registers matching datasets internally.

Following parameters can be used to tune the search
- `q` → free-text query  
- `bbox` → geographic bounding box (minlon, minlat, maxlon, maxlat)  
- `keywords` → optional provider-specific terms

In [ ]:
ds = dataset.search_studies(
    q="Khider, D.",
    # bbox=(-10, -10, 10, 10),  #(min_lon, min_lat, max_lon, max_lat) 
    # keywords=["Sr/Ca"],
    limit=10
)

[2026-03-24 12:40:26,623][INFO] - Retrived 10 studies
[2026-03-24 12:40:26,629][WARNING] - The search contains dataset(s) [830589, 897517] marked as collection. Refer to the 'CollectionMembers' column toidentify respective child datasets.

### 2. EXPLORING RESULTS

#### a. Getting a summary.

You can access the search results in two ways:
- `dataset.get_summary()` → returns a DataFrame of search results (default behavior)
- ACCESS the DataFrame in return value. i.e. `ds`

All results are stored internally in `dataset.studies`

In [ ]:
dataset.get_summary()

[2026-03-24 12:40:26,647][WARNING] - The search contains dataset(s) [830589, 897517] marked as collection. Refer to the 'CollectionMembers' column toidentify respective child datasets.

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,830589,Stable isotope record of sediment core MD98-2177,NaN,NaN,NaN,NaN,We present a reconstruction of El Niño Souther...,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],"[830586, 830587, 830588]"
1,897517,Globigerinoides ruber sediment trap data in th...,NaN,NaN,NaN,NaN,We present results here from a high-resolution...,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[],[],"[897509, 897512, 897513, 897514, 897515, 897516]"
2,830588,(Table 3) Lead 214 and Lead 210 concentration ...,NaN,NaN,NaN,NaN,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
3,897512,Globigerinoides ruber flux analysis from a lon...,NaN,NaN,NaN,NaN,None,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
4,897516,CTD data from a long-running sediment trap tim...,NaN,NaN,NaN,NaN,None,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
5,897514,Magnesium/Calcium ratio of Globigerinoides rub...,NaN,NaN,NaN,NaN,None,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
6,830587,(Table 2) Age determination of sediment core M...,98.0,1950.0,0.0,1852.0,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
7,830586,(Table S1) Stable carbon and oxygen isotope ra...,1231.0,103.0,704.0,1851.0,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
8,897509,Carbonate measurements from a long-running sed...,NaN,NaN,NaN,NaN,None,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
9,897513,Isotpes analysis of Globigerinoides ruber from...,NaN,NaN,NaN,NaN,None,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None

#### b. Exploring Geographic Metadata

Returns site-level geographic information where available.

If no geospatial metadata exists, an empty DataFrame is returned.

In [ ]:
geo = dataset.get_geo()
display(geo)

,StudyID,SiteID,SiteName,LocationName,Latitude,Longitude,Elevation
0,830589,2013989,MD98-2177,None,1.4,119.08,-968.0
1,830588,2013989,MD98-2177,None,1.4,119.08,-968.0
2,897512,2901221,GMT_Gulf_of_Mexico,Gulf of Mexico,27.5,-90.30,-700.0
3,897516,2901221,GMT_Gulf_of_Mexico,Gulf of Mexico,27.5,-90.30,-700.0
4,897514,2901221,GMT_Gulf_of_Mexico,Gulf of Mexico,27.5,-90.30,-700.0
5,830587,2013989,MD98-2177,None,1.4,119.08,-968.0
6,830586,2013989,MD98-2177,None,1.4,119.08,-968.0
7,897509,2901221,GMT_Gulf_of_Mexico,Gulf of Mexico,27.5,-90.30,-700.0
8,897513,2901221,GMT_Gulf_of_Mexico,Gulf of Mexico,27.5,-90.30,-700.0

#### c. Explore the listed Publication

In [ ]:
pubs = dataset.get_publications()
display(pubs)

(BibliographyData(
   entries=OrderedCaseInsensitiveDict([
     ('10_1594_PANGAEA_830589_1_1', Entry('misc',
       fields=[
         ('title', 'Stable isotope record of sediment core MD98-2177'),
         ('year', '2011'),
         ('doi', '10.1594/PANGAEA.830589'),
         ('url', 'https://doi.org/10.1594/PANGAEA.830589')],
       persons={'author': [Person('Khider'), Person('D'), Person('Stott'), Person('D, Lowell'), Person('Emile-Geay'), Person('J'), Person('Thunell'), Person('C, Robert'), Person('Hammond'), Person('E, Douglas')]})),
     ('10_1594_PANGAEA_897517_1_2', Entry('misc',
       fields=[
         ('title', 'Globigerinoides ruber sediment trap data in the Gulf of Mexico'),
         ('year', '2019'),
         ('doi', '10.1594/PANGAEA.897517'),
         ('url', 'https://doi.org/10.1594/PANGAEA.897517')],
       persons={'author': [Person('Richey'), Person('N, Julie'), Person('Thirumalai'), Person('Kaustubh'), Person('Khider'), Person('D'), Person('Reynolds'), Person('E, Caitlin'), Person('Partin'), Person('W, Judson'), Person('Quinn'), Person('Michael, Terrence')]})),
     ('10_1594_PANGAEA_830588_1_3', Entry('misc',
       fields=[
         ('title', '(Table 3) Lead 214 and Lead 210 concentration of sediment core MD98-2177'),
         ('year', '2011'),
         ('doi', '10.1594/PANGAEA.830588'),
         ('url', 'https://doi.org/10.1594/PANGAEA.830588')],
       persons={'author': [Person('Khider'), Person('D'), Person('Stott'), Person('D, Lowell'), Person('Emile-Geay'), Person('J'), Person('Thunell'), Person('C, Robert'), Person('Hammond'), Person('E, Douglas')]})),
     ('10_1594_PANGAEA_897512_1_4', Entry('misc',
       fields=[
         ('title', 'Globigerinoides ruber flux analysis from a long-running sediment trap time series from the northern Gulf of Mexico'),
         ('year', '2019'),
         ('doi', '10.1594/PANGAEA.897512'),
         ('url', 'https://doi.org/10.1594/PANGAEA.897512')],
       persons={'author': [Person('Richey'), Person('N, Julie'), Person('Thirumalai'), Person('Kaustubh'), Person('Khider'), Person('D'), Person('Reynolds'), Person('E, Caitlin'), Person('Partin'), Person('W, Judson'), Person('Quinn'), Person('Michael, Terrence')]})),
     ('10_1594_PANGAEA_897516_1_5', Entry('misc',
       fields=[
         ('title', 'CTD data from a long-running sediment trap time series from the northern Gulf of Mexico'),
         ('year', '2019'),
         ('doi', '10.1594/PANGAEA.897516'),
         ('url', 'https://doi.org/10.1594/PANGAEA.897516')],
       persons={'author': [Person('Richey'), Person('N, Julie'), Person('Thirumalai'), Person('Kaustubh'), Person('Khider'), Person('D'), Person('Reynolds'), Person('E, Caitlin'), Person('Partin'), Person('W, Judson'), Person('Quinn'), Person('Michael, Terrence')]})),
     ('10_1594_PANGAEA_897514_1_6', Entry('misc',
       fields=[
         ('title', 'Magnesium/Calcium ratio of Globigerinoides ruber from a long-running sediment trap time series from the northern Gulf of Mexico'),
         ('year', '2019'),
         ('doi', '10.1594/PANGAEA.897514'),
         ('url', 'https://doi.org/10.1594/PANGAEA.897514')],
       persons={'author': [Person('Richey'), Person('N, Julie'), Person('Thirumalai'), Person('Kaustubh'), Person('Khider'), Person('D'), Person('Reynolds'), Person('E, Caitlin'), Person('Partin'), Person('W, Judson'), Person('Quinn'), Person('Michael, Terrence')]})),
     ('10_1594_PANGAEA_830587_1_7', Entry('misc',
       fields=[
         ('title', '(Table 2) Age determination of sediment core MD98-2177'),
         ('year', '2011'),
         ('doi', '10.1594/PANGAEA.830587'),
         ('url', 'https://doi.org/10.1594/PANGAEA.830587')],
       persons={'author': [Person('Khider'), Person('D'), Person('Stott'), Person('D, Lowell'), Person('Emile-Geay'), Person('J'), Person('Thunell'), Person('C, Robert'), Person('Hammond'), Person('E, Douglas')]})),
     ('10_1594_PANGAEA_830586_1_8', Entry('misc',
       fields=[
         ('title', '(Table S1) Stable carbon and oxygen isotope ratios of Pulleniatina obliquiloculata of sediment core MD98-2177'),
         ('year', '2011'),
         ('doi', '10.1594/PANGAEA.830586'),
         ('url', 'https://doi.org/10.1594/PANGAEA.830586')],
       persons={'author': [Person('Khider'), Person('D'), Person('Stott'), Person('D, Lowell'), Person('Emile-Geay'), Person('J'), Person('Thunell'), Person('C, Robert'), Person('Hammond'), Person('E, Douglas')]})),
     ('10_1594_PANGAEA_897509_1_9', Entry('misc',
       fields=[
         ('title', 'Carbonate measurements from a long-running sediment trap time series from the northern Gulf of Mexico'),
         ('year', '2019'),
         ('doi', '10.1594/PANGAEA.897509'),
         ('url', 'https://doi.org/10.1594/PANGAEA.897509')],
       persons={'author': [Person('Richey'), Person('N, Julie'), Person('Thirumalai'), Person('Kaustubh'), Person('Khider'), Person('D'), Person('Reynolds'), Person('E, Caitlin'), Person('Partin'), Person('W, Judson'), Person('Quinn'), Person('Michael, Terrence')]})),
     ('10_1594_PANGAEA_897513_1_10', Entry('misc',
       fields=[
         ('title', 'Isotpes analysis of Globigerinoides ruber from a long-running sediment trap time series from the northern Gulf of Mexico'),
         ('year', '2019'),
         ('doi', '10.1594/PANGAEA.897513'),
         ('url', 'https://doi.org/10.1594/PANGAEA.897513')],
       persons={'author': [Person('Richey'), Person('N, Julie'), Person('Thirumalai'), Person('Kaustubh'), Person('Khider'), Person('D'), Person('Reynolds'), Person('E, Caitlin'), Person('Partin'), Person('W, Judson'), Person('Quinn'), Person('Michael, Terrence')]}))]),

   preamble=[]),
     StudyID                                          StudyName  \
 0    830589   Stable isotope record of sediment core MD98-2177
 1    830589   Stable isotope record of sediment core MD98-2177
 2    897517  Globigerinoides ruber sediment trap data in th...
 3    897517  Globigerinoides ruber sediment trap data in th...
 4    830588  (Table 3) Lead 214 and Lead 210 concentration ...
 5    897512  Globigerinoides ruber flux analysis from a lon...
 6    897516  CTD data from a long-running sediment trap tim...
 7    897514  Magnesium/Calcium ratio of Globigerinoides rub...
 8    830587  (Table 2) Age determination of sediment core M...
 9    830586  (Table S1) Stable carbon and oxygen isotope ra...
 10   897509  Carbonate measurements from a long-running sed...
 11   897513  Isotpes analysis of Globigerinoides ruber from...

                                                Author  \
 0   Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...
 1                                                None
 2   Richey, Julie N; Thirumalai, Kaustubh; Khider,...
 3                                                None
 4   Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...
 5   Richey, Julie N; Thirumalai, Kaustubh; Khider,...
 6   Richey, Julie N; Thirumalai, Kaustubh; Khider,...
 7   Richey, Julie N; Thirumalai, Kaustubh; Khider,...
 8   Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...
 9   Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...
 10  Richey, Julie N; Thirumalai, Kaustubh; Khider,...
 11  Richey, Julie N; Thirumalai, Kaustubh; Khider,...

                                                 Title  Journal  Year Volume  \
 0    Stable isotope record of sediment core MD98-2177  PANGAEA  2011   None
 1   Khider, D et al. (2011): Assessing El Niño Sou...     None  2011   None
 2   Globigerinoides ruber sediment trap data in th...  PANGAEA  2019   None
 3   Richey, JN et al. (2019): Considerations for G...     None  2019   None
 4   (Table 3) Lead 214 and Lead 210 concentration ...  PANGAEA  2011   None
 5   Globigerinoides ruber flux analysis from a lon...  PANGAEA  2019   None
 6   CTD data from a long-running sediment trap tim...  PANGAEA  2019   None
 7   Magnesium/Calcium ratio of Globigerinoides rub...  PANGAEA  2019   None
 8   (Table 2) Age determination of sediment core M...  PANGAEA  2011   None
 9   (Table S1) Stable carbon and oxygen isotope ra...  PANGAEA  2011   None
 10  Carbonate measurements from a long-running sed...  PANGAEA  2019   None
 11  Isotpes analysis of Globigerinoides ruber from...  PANGAEA  2019   None

    Number Pages     Type                     DOI  \
 0    None  None  dataset  10.1594/PANGAEA.830589
 1    None  None  article    10.1029/2011PA002139
 2    None  None  dataset  10.1594/PANGAEA.897517
 3    None  None  article    10.1029/2018PA003417
 4    None  None  dataset  10.1594/PANGAEA.830588
 5    None  None  dataset  10.1594/PANGAEA.897512
 6    None  None  dataset  10.1594/PANGAEA.897516
 7    None  None  dataset  10.1594/PANGAEA.897514
 8    None  None  dataset  10.1594/PANGAEA.830587
 9    None  None  dataset  10.1594/PANGAEA.830586
 10   None  None  dataset  10.1594/PANGAEA.897509
 11   None  None  dataset  10.1594/PANGAEA.897513

                                        URL  \
 0   https://doi.org/10.1594/PANGAEA.830589
 1                                     None
 2   https://doi.org/10.1594/PANGAEA.897517
 3                                     None
 4   https://doi.org/10.1594/PANGAEA.830588
 5   https://doi.org/10.1594/PANGAEA.897512
 6   https://doi.org/10.1594/PANGAEA.897516
 7   https://doi.org/10.1594/PANGAEA.897514
 8   https://doi.org/10.1594/PANGAEA.830587
 9   https://doi.org/10.1594/PANGAEA.830586
 10  https://doi.org/10.1594/PANGAEA.897509
 11  https://doi.org/10.1594/PANGAEA.897513

                                           CitationKey
 0   Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...
 1   Khider, D et al. (2011): Assessing El Niño Sou...
 2   Richey, Julie N; Thirumalai, Kaustubh; Khider,...
 3   Richey, JN et al. (2019): Considerations for G...
 4   Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...
 5   Richey, Julie N; Thirumalai, Kaustubh; Khider,...
 6   Richey, Julie N; Thirumalai, Kaustubh; Khider,...
 7   Richey, Julie N; Thirumalai, Kaustubh; Khider,...
 8   Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...
 9   Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...
 10  Richey, Julie N; Thirumalai, Kaustubh; Khider,...
 11  Richey, Julie N; Thirumalai, Kaustubh; Khider,...  )

Save the publications directly to bibtex. Follwoing saves the publications to a file named `pangaea-datasets.bib` in your workng directory. Alter the path to save to your desired location

In [ ]:
save = dataset.get_publications(save = True, path="./pnagaea-datasets.bib")

### 3. Extract Data from studies

In [ ]:
dataset.get_summary()

[2026-03-24 12:53:26,636][WARNING] - The search contains dataset(s) [830589, 897517] marked as collection. Refer to the 'CollectionMembers' column toidentify respective child datasets.

,StudyID,StudyName,EarliestYearBP,MostRecentYearBP,EarliestYearCE,MostRecentYearCE,StudyNotes,ScienceKeywords,Investigators,Publications,Sites,Funding,CollectionMembers
0,830589,Stable isotope record of sediment core MD98-2177,NaN,NaN,NaN,NaN,We present a reconstruction of El Niño Souther...,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],"[830586, 830587, 830588]"
1,897517,Globigerinoides ruber sediment trap data in th...,NaN,NaN,NaN,NaN,We present results here from a high-resolution...,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[],[],"[897509, 897512, 897513, 897514, 897515, 897516]"
2,830588,(Table 3) Lead 214 and Lead 210 concentration ...,NaN,NaN,NaN,NaN,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
3,897512,Globigerinoides ruber flux analysis from a lon...,NaN,NaN,NaN,NaN,None,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
4,897516,CTD data from a long-running sediment trap tim...,NaN,NaN,NaN,NaN,None,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
5,897514,Magnesium/Calcium ratio of Globigerinoides rub...,NaN,NaN,NaN,NaN,None,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
6,830587,(Table 2) Age determination of sediment core M...,98.0,1950.0,0.0,1852.0,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
7,830586,(Table S1) Stable carbon and oxygen isotope ra...,1231.0,103.0,704.0,1851.0,None,[],"Khider, D, Stott, Lowell D, Emile-Geay, J, Thu...","Khider, D; Stott, Lowell D; Emile-Geay, J; Thu...",[MD98-2177],[],None
8,897509,Carbonate measurements from a long-running sed...,NaN,NaN,NaN,NaN,None,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None
9,897513,Isotpes analysis of Globigerinoides ruber from...,NaN,NaN,NaN,NaN,None,[],"Richey, Julie N, Thirumalai, Kaustubh, Khider,...","Richey, Julie N; Thirumalai, Kaustubh; Khider,...",[GMT_Gulf_of_Mexico],[],None

In [ ]:
dfs = dataset.get_data([830586, 830587])

In [ ]:
for df in dfs:
    print(df.head())

   Depth sed  Depth top  Depth bot   Age  Age_2  Age_3  \
0      0.005        0.0       0.01  1843   1851  0.103
1      0.005        0.0       0.01  1843   1851  0.103
2      0.005        0.0       0.01  1843   1851  0.103
3      0.005        0.0       0.01  1843   1851  0.103
4      0.005        0.0       0.01  1843   1851  0.103

   P. obliquiloculata δ13C  P. obliquiloculata δ18O  Mass      Event  \
0                    0.936                   -2.254    34  MD98-2177
1                    0.895                   -2.356    37  MD98-2177
2                    0.514                   -2.630    20  MD98-2177
3                    0.900                   -2.480    25  MD98-2177
4                    0.957                   -2.094    29  MD98-2177

   Latitude  Longitude  Elevation Date/Time
0       1.4     119.08     -968.0       NaT
1       1.4     119.08     -968.0       NaT
2       1.4     119.08     -968.0       NaT
3       1.4     119.08     -968.0       NaT
4       1.4     119.08     -968.0       NaT
   Depth sed                                     Lab Lab label  Age dated  \
0       0.00  Lawrence Livermore National Laboratory     95299      0.580
1       0.12        University of California, Irvine  OS-38302      0.395
2       0.50  Lawrence Livermore National Laboratory    100234      1.110
3       0.94  Lawrence Livermore National Laboratory    100235      1.745
4       1.09        University of California, Irvine  OS-38335      1.870

   Age dated std dev   Age  Age e    Comm      Event  Latitude  Longitude  \
0              0.045  1852     51     NaN  MD98-2177       1.4     119.08
1              0.090     0      0  modern  MD98-2177       1.4     119.08
2              0.060  1350     70     NaN  MD98-2177       1.4     119.08
3              0.045   730     82     NaN  MD98-2177       1.4     119.08
4              0.110   584    136     NaN  MD98-2177       1.4     119.08

   Elevation Date/Time
0     -968.0       NaT
1     -968.0       NaT
2     -968.0       NaT
3     -968.0       NaT
4     -968.0       NaT